name: "CLA"
on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened,closed,synchronize]
permissions:
  pull-requests: write
  issues: write
jobs:
  CLAAssistant:
    runs-on: ubuntu-latest
    steps:
      - name: Generate App token
        id: generated_token
        uses: tibdex/github-app-token@v2.1.0
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
      - name: "CLA Assistant"
        if: (github.event.comment.body == 'recheck' || github.event.comment.body == 'I have read the CLA Document and I hereby sign the CLA') || github.event_name == 'pull_request_target'
        # Beta Release
        uses: contributor-assistant/github-action@v2.3.2
        env:
          GITHUB_TOKEN: ${{ steps.generated_token.outputs.token }}
          # the below token should have repo scope and must be manually added by you in the repository's secret
          PERSONAL_ACCESS_TOKEN: ${{ steps.generated_token.outputs.token }}
        with:
          path-to-signatures: 'signatures-v2.json'
          path-to-document: 'https://github.com/is-cool-me/register/blob/main/terms.md' # e.g. a CLA or a DCO document
          # branch should not be protected
          branch: 'main'
          allowlist: is-cool-me[bot],bot*
          remote-organization-name: 'is-cool-me'
          remote-repository-name: 'cla'
